### ISSUE TITLE
ParseExactConverter for UpdatedAt field in Greeks is bad

### ISSUE THREAD

**Issue by tinytownsoftware** [vitali-karmanov/tradier-dotnet-client#3]
Reading works fine, but writing produces invalid json. Json will look like:

```
"greeks": {
	"delta": 0.0,
	"gamma": 0.0,
	"theta": 0.0,
	"vega": 2E-05,
	"rho": 0.0,
	"phi": 0.0,
	"bid_iv": 0.0,
	"mid_iv": 0.9879,
	"ask_iv": 1.9758,
	"smv_vol": 0.479,
	"updated_at": 9 / 29 / 2020 7: 56: 01 PM
}
```

You could probably just use MillisecondsEpochConverter like for other fields, which works just fine.

**Comment by vitali-karmanov** [comment]
Hello @tinytownsoftware, thank you for reaching out with this!

You were right, the UpdatedAt was producing an invalid JSON. However, the problem was happening because the WriteRawValue function was missing the double quotes to write the date as a string.

Nevertheless, I just published a new version of the NuGet Package (1.0.7) with the fix and this should be working now.

Thank you again and let me know if you see any other problems!
